# version: '3.8'

# services:
#   keycloak:
#     image: quay.io/keycloak/keycloak:25.0.1
#     container_name: dummy_keycloak3
#     environment:
#       - DB_VENDOR=mysql
#       - DB_ADDR=mysql_container_for_keycloak3
#       - DB_PORT=3308
#       - DB_DATABASE=keycloak
#       - DB_USER=keycloak
#       - DB_PASSWORD=password
#       - KEYCLOAK_USER=admin
#       - KEYCLOAK_PASSWORD=admin
#       - KEYCLOAK_ADMIN=admin
#       - KEYCLOAK_ADMIN_PASSWORD=admin
#       - KEYCLOAK_IMPORT=/opt/keycloak/data/realm-export.json
#       - KEYCLOAK_LOGLEVEL=DEBUG
#       - SMTP_HOST=172.17.0.1
#       - SMTP_PORT=1025
#       - SMTP_FROM=no-reply@example.com
#       - SMTP_USER=smtp_user
#       - SMTP_PASSWORD=smtp_password
#       - JDBC_PARAMS=useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#       - KC_RUN_IN_CONTAINER=true
#       - KAFKA_BROKER=kafka:9092  # Add this to configure the Kafka broker
#     ports:
#       - "8003:8080"
#     volumes:
#       - "C:/Users/anuma/Downloads/keycloak-25.0.1/keycloak-25.0.1/bin:/opt/keycloak/bin"
#       - "C:/Users/anuma/Downloads/keycloak-25.0.1/keycloak-25.0.1/data:/opt/keycloak/data"
#       - "C:/Users/anuma/Downloads/keycloak-25.0.1/keycloak-25.0.1/conf for docker/conf:/opt/keycloak/conf"
#       - "D:/docker-learnings/keycloak compose file/provider:/opt/keycloak/providers"
#     command: ["start-dev"]
#     networks:
#       - keycloak-network
#     depends_on:
#       - mysql
#       - kafka  # Ensure Kafka is started before Keycloak

#   mysql:
#     image: mysql:8.0.33
#     container_name: mysql_container_for_keycloak3
#     environment:
#       - MYSQL_ROOT_PASSWORD=password
#       - MYSQL_DATABASE=keycloak
#       - MYSQL_USER=keycloak
#       - MYSQL_PASSWORD=password
#     ports:
#       - "3308:3306"
#     volumes:
#       - mysql_vol_for_keycloak:/var/lib/mysql
#     networks:
#       - keycloak-network

#   zookeeper:
#     image: confluentinc/cp-zookeeper:7.4.0
#     container_name: zookeeper
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#     ports:
#       - "2181:2181"
#     networks:
#       - keycloak-network

#   kafka:
#     image: confluentinc/cp-kafka:7.4.0
#     container_name: kafka
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
#       KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL_SAME_HOST://0.0.0.0:29092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#     ports:
#       - "9092:9092"
#       - "29092:29092"
#     depends_on:
#       - zookeeper
#     networks:
#       - keycloak-network


# networks:
#   keycloak-network:
#     driver: bridge

# volumes:
#   mysql_vol_for_keycloak:
version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: dummy_keycloak3
    environment:
      - TZ=Asia/Kolkata
      - DB_VENDOR=mysql
      - DB_ADDR=mysql_container_for_keycloak3
      - DB_PORT=3308
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/realm-export.json
      - KEYCLOAK_LOGLEVEL=DEBUG
      - SMTP_HOST=172.17.0.1
      - SMTP_PORT=1025
      - SMTP_FROM=no-reply@example.com
      - SMTP_USER=smtp_user
      - SMTP_PASSWORD=smtp_password
      - JDBC_PARAMS=useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - KC_RUN_IN_CONTAINER=true
      - KAFKA_BROKER=kafka:9092  # Add this to configure the Kafka broker
    ports:
      - "8003:8080"
    volumes:
      - "C:/Users/anuma/Downloads/keycloak-25.0.1/keycloak-25.0.1/bin:/opt/keycloak/bin"
      - "C:/Users/anuma/Downloads/keycloak-25.0.1/keycloak-25.0.1/data:/opt/keycloak/data"
      - "C:/Users/anuma/Downloads/keycloak-25.0.1/keycloak-25.0.1/conf for docker/conf:/opt/keycloak/conf"
      # - "D:/docker-learnings/keycloak compose file/provider/new:/opt/keycloak/providers"
    command: ["start-dev"]
    networks:
      - keycloak-network
    depends_on:
      - mysql
      - kafka  # Ensure Kafka is started before Keycloak

  mysql:
    image: mysql:8.0.33
    container_name: mysql_container_for_keycloak3
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    ports:
      - "3308:3306"
    volumes:
      - mysql_vol_for_keycloak:/var/lib/mysql
    networks:
      - keycloak-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - keycloak-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL_SAME_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    networks:
      - keycloak-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8071:8081"  # Map external port 8071 to internal port 8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:9092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081  # Keep the internal listener on 8081
    networks:
      - keycloak-network

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.4.0
    container_name: control-center
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:9092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'  # Internal port
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1
    networks:
      - keycloak-network

  redis:
    image: redis:7.0.11
    container_name: redis
    ports:
      - "6479:6379"
    networks:
      - keycloak-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    depends_on:
      - redis
    ports:
      - "5540:5540"
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  mysql_vol_for_keycloak:
