version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: dummy_keycloak3
    environment:
      - TZ=Asia/Kolkata
      - DB_VENDOR=mysql
      - DB_ADDR=mysql_container_for_keycloak3
      - DB_PORT=3308
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/realm-export.json
      - KEYCLOAK_LOGLEVEL=DEBUG
      - SMTP_HOST=172.17.0.1
      - SMTP_PORT=1025
      - SMTP_FROM=no-reply@example.com
      - SMTP_USER=smtp_user
      - SMTP_PASSWORD=smtp_password
      - JDBC_PARAMS=useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - KC_RUN_IN_CONTAINER=true
    ports:
      - "8003:8080"
    volumes:
      - "C:/Users/anuma/Downloads/keycloak-25.0.1/keycloak-25.0.1/bin:/opt/keycloak/bin"
      - "C:/Users/anuma/Downloads/keycloak-25.0.1/keycloak-25.0.1/data:/opt/keycloak/data"
      - "C:/Users/anuma/Downloads/keycloak-25.0.1/keycloak-25.0.1/conf for docker/conf:/opt/keycloak/conf"
    command: ["start-dev"]
    networks:
      - keycloak-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.33
    container_name: mysql_container_for_keycloak3
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    ports:
      - "3308:3306"
    volumes:
      - mysql_vol_for_keycloak:/var/lib/mysql
    networks:
      - keycloak-network


networks:
  keycloak-network:
    driver: bridge

volumes:
  mysql_vol_for_keycloak:
