spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8003/realms/QEats/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: qeats-app
            client-secret: zQxv2S2UM9hALb3rjz5cbqVN1yTGVbOd
            redirectUri: "{baseUrl}/login/oauth2/code/keycloak"
            authorization-grant-type: authorization_code
            scope: openid, profile, email, message.read
        provider:
          keycloak:
            realm: QEats
            issuer-uri: http://localhost:8003/realms/QEats
            authorizationUri: http://localhost:8003/realms/QEats/protocol/openid-connect/auth
            tokenUri: http://localhost:8003/realms/QEats/protocol/openid-connect/token
            userInfoUri: http://localhost:8003/realms/QEats/protocol/openid-connect/userinfo
            jwkSetUri: http://localhost:8003/realms/QEats/protocol/openid-connect/certs
            logoutUri: http://localhost:8003/realms/QEats/protocol/openid-connect/logout

    application:
      name: api-gateway
    main:
      web-application-type: reactive
      allow-bean-definition-overriding: true
    cloud:
      gateway:
  #
  #      #      routes:
  #      #        - id: auth-service
  #      #          uri: lb://AUTH-SERVICE
  #      #          predicates:
  #      #            - Path=/auth/**
  #
        discovery:
          locator:
            enabled: true

#
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000"
#            allowedMethods:
#              - GET
#              - POST
#              - DELETE
#              - PUT
#            allowedHeaders: '*'
#            maxAge: 30
#            allowCredentials: true


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    urls:
      - name: User Service
        url: http://localhost:8085/v3/api-docs
      - name: Restaurant Service
        url: http://localhost:8086/v3/api-docs
    path: /swagger-ui.html


server:
  port: 8765
#  servlet:
#    session:
#      cookie:
#        same-site: lax

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
        oauth2:
          client: DEBUG
        web: DEBUG
        reactive:
          function:
            client: DEBUG
    root: info
  pattern:
    console: ${logpattern-console:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  color:
    console:
      highlight:
        FATAL: "red blink"
        ERROR: "red"
        WARN: "yellow bold"
        INFO: "green"
        DEBUG: "blue"
        TRACE: "magenta"
jwt:
  secret-key: iojicmIPOInIpInMIObdfijOInOndIOBemiojicmIPOInIpInMIObdfijOInOndIOBemPMoicejOInOndIOBemPMoice

