spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qeats_orders_test
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.eureka.EurekaClientAutoConfiguration

eureka:
  client:
    enabled: false


